[package]
name = "boot-manipulator"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
uefi = "0.32.0"

[lints]
workspace = true
