[package]
name = "boot-manipulator"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[features]

[dependencies]
uefi = "*"

[lints]
workspace = true
