[package]
name = "boot-manipulator"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
log = "0.4.22"

[target.'cfg(target_os = "uefi")'.dependencies]
uefi = "0.32.0"

[lints]
workspace = true
